---
- name: Configure nginx web server
  hosts: webserver
  tasks: 
  - name: install ngnix server
    yum: 
      name: nginx
      state: latest
  - name: start the installed ngnix
    service:
      name: nginx
      state: started