---
- name: Configure nginx web server
  hosts: webserver
  tasks: 
  - name: install EPEL repository
    become: yes
    yum: 
      name: epel-release 
      state: present
  - name: install ngnix server
    yum: 
      name: nginx
      state: latest
  - name: start the installed ngnix
    service:
      name: nginx
      state: started